## Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

print("TensorFlow Version:", tf.__version__)

TensorFlow Version: 2.20.0

## Load Dataset

In [2]:
df = pd.read_csv('bengaluru_house_prices.csv')

df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

## Data Preprocessing & Cleaning

In [3]:
df = df.drop(columns=['area_type', 'availability', 'society', 'balcony'])

df = df.dropna()

df['bhk'] = df['size'].apply(lambda x: int(x.split(' ')[0]))
df = df.drop(columns=['size'])

def convert_sqft_to_num(x):
    tokens = str(x).split('-')
    if len(tokens) == 2:
        return (float(tokens[0]) + float(tokens[1])) / 2
    try:
        return float(x)
    except:
        return None

df['total_sqft'] = df['total_sqft'].apply(convert_sqft_to_num)
df = df.dropna()

location_stats = df['location'].value_counts()
locations_less_than_10 = location_stats[location_stats <= 10]
df['location'] = df['location'].apply(lambda x: 'other' if x in locations_less_than_10 else x)

df = pd.get_dummies(df, columns=['location'], drop_first=True, dtype=int)

df.head()

,total_sqft,bath,price,bhk,location_1st Block Jayanagar,location_1st Phase JP Nagar,location_2nd Phase Judicial Layout,location_2nd Stage Nagarbhavi,location_5th Block Hbr Layout,location_5th Phase JP Nagar,...,location_Vishveshwarya Layout,location_Vishwapriya Layout,location_Vittasandra,location_Whitefield,location_Yelachenahalli,location_Yelahanka,location_Yelahanka New Town,location_Yelenahalli,location_Yeshwanthpur,location_other
0,1056.0,2.0,39.07,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2600.0,5.0,120.00,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1440.0,2.0,62.00,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1521.0,3.0,95.00,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1200.0,2.0,51.00,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Split Data & Feature Scaling

In [4]:
X = df.drop(columns=['price'])
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"X_train shape: {X_train_scaled.shape}")

X_train shape: (10560, 243)

## Build ANN Model

In [5]:
model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dropout(0.2),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse', metrics=['mae'])

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │        31,232 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 41,601 (162.50 KB)

 Trainable params: 41,601 (162.50 KB)

 Non-trainable params: 0 (0.00 B)

## Train the Model

In [6]:
history = model.fit(X_train_scaled, y_train,
                    validation_split=0.2,
                    epochs=60,
                    batch_size=32,
                    verbose=1)

Epoch 1/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 20488.9375 - mae: 67.4978 - val_loss: 18105.9590 - val_mae: 55.5558
Epoch 2/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 14062.2129 - mae: 48.1749 - val_loss: 17381.7500 - val_mae: 43.8582
Epoch 3/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12974.8975 - mae: 45.0209 - val_loss: 16336.7598 - val_mae: 43.4360
Epoch 4/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12877.5479 - mae: 44.4407 - val_loss: 17313.9219 - val_mae: 46.0210
Epoch 5/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12191.4678 - mae: 43.2102 - val_loss: 15861.9502 - val_mae: 47.6475
Epoch 6/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12344.6299 - mae: 43.2655 - val_loss: 15597.4756 - val_mae: 44.4768
Epoch 7/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12279.6943 - mae: 43.8684 - val_loss: 15298.5898 - val_mae: 40.4642
Epoch 8/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11738.7891 - mae: 42.7369 - val_loss: 15229.4531 - val_mae: 40.1051
Epoch 9/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11706.7539 - mae: 41.9929 - val_loss: 14688.5195 - val_mae: 40.0223
Epoch 10/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11223.7197 - mae: 41.0439 - val_loss: 14765.0068 - val_mae: 42.8711
Epoch 11/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11216.3984 - mae: 41.0136 - val_loss: 14969.9092 - val_mae: 40.6546
Epoch 12/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10745.4053 - mae: 40.1851 - val_loss: 14020.7920 - val_mae: 38.0843
Epoch 13/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10534.0684 - mae: 39.4117 - val_loss: 13801.3350 - val_mae: 37.8863
Epoch 14/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10458.7910 - mae: 39.6016 - val_loss: 13829.7158 - val_mae: 37.7896
Epoch 15/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10352.2080 - mae: 39.5016 - val_loss: 13378.5479 - val_mae: 37.9227
Epoch 16/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9942.3926 - mae: 38.8473 - val_loss: 13461.8154 - val_mae: 37.1829
Epoch 17/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9760.0273 - mae: 38.7961 - val_loss: 13078.6006 - val_mae: 39.7653
Epoch 18/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9795.7012 - mae: 38.0685 - val_loss: 12974.6914 - val_mae: 37.6090
Epoch 19/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9718.8770 - mae: 38.5411 - val_loss: 12619.7148 - val_mae: 37.8396
Epoch 20/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8949.1084 - mae: 37.9734 - val_loss: 13506.8086 - val_mae: 45.3389
Epoch 21/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9196.5420 - mae: 37.6134 - val_loss: 12482.6709 - val_mae: 39.0493
Epoch 22/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9324.6562 - mae: 37.3152 - val_loss: 13251.7100 - val_mae: 37.6798
Epoch 23/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9444.4883 - mae: 38.1129 - val_loss: 12230.7891 - val_mae: 36.4343
Epoch 24/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8676.5166 - mae: 37.1093 - val_loss: 12645.0986 - val_mae: 37.1345
Epoch 25/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9101.0791 - mae: 37.3573 - val_loss: 12703.4326 - val_mae: 36.6078
Epoch 26/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8865.7256 - mae: 37.4621 - val_loss: 12157.0234 - val_mae: 37.5517
Epoch 27/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8903.0264 - mae: 36.6302 - val_loss: 12375.6084 - val_mae: 35.9924
Epoch 28/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8593.0723 - mae: 36.5970 - val_loss: 11978.8398 - val_mae: 38.0366
Epoch 29/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8639.5059 - mae: 36.8201 - val_loss: 11499.8291 - val_mae: 36.5517
Epoch 30/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8468.6133 - mae: 36.4734 - val_loss: 11625.5010 - val_mae: 36.5127
Epoch 31/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8736.2295 - mae: 36.6857 - val_loss: 11568.3555 - val_mae: 35.9743
Epoch 32/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7801.8359 - mae: 35.9506 - val_loss: 12023.9219 - val_mae: 35.6298
Epoch 33/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7921.6997 - mae: 35.9643 - val_loss: 11758.3750 - val_mae: 35.7104
Epoch 34/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8823.4141 - mae: 36.4939 - val_loss: 12103.1641 - val_mae: 37.4522
Epoch 35/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8162.5557 - mae: 36.0062 - val_loss: 11448.1035 - val_mae: 35.8480
Epoch 36/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8051.2510 - mae: 36.0715 - val_loss: 11896.4531 - val_mae: 36.0343
Epoch 37/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7591.4097 - mae: 35.3630 - val_loss: 11563.7783 - val_mae: 37.4641
Epoch 38/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7388.8281 - mae: 35.6648 - val_loss: 12153.9736 - val_mae: 42.7240
Epoch 39/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7940.0776 - mae: 36.1784 - val_loss: 11018.7080 - val_mae: 37.1905
Epoch 40/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7896.0635 - mae: 36.7283 - val_loss: 11172.8623 - val_mae: 37.1291
Epoch 41/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7966.8477 - mae: 35.8235 - val_loss: 12013.0449 - val_mae: 36.8289
Epoch 42/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7696.6172 - mae: 35.9682 - val_loss: 11238.7236 - val_mae: 39.7893
Epoch 43/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7742.8047 - mae: 35.5410 - val_loss: 11395.6621 - val_mae: 36.4883
Epoch 44/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8106.4639 - mae: 35.4478 - val_loss: 10780.2002 - val_mae: 37.1838
Epoch 45/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7526.0811 - mae: 34.7367 - val_loss: 11655.7012 - val_mae: 37.7828
Epoch 46/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7394.7417 - mae: 35.6212 - val_loss: 12879.7930 - val_mae: 37.3550
Epoch 47/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7719.8726 - mae: 34.7921 - val_loss: 13227.6426 - val_mae: 38.3243
Epoch 48/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7427.3032 - mae: 34.3704 - val_loss: 10917.9326 - val_mae: 38.0159
Epoch 49/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7507.0278 - mae: 34.6442 - val_loss: 11234.2549 - val_mae: 35.7412
Epoch 50/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7645.2666 - mae: 34.9453 - val_loss: 11215.5654 - val_mae: 36.7573
Epoch 51/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7027.2231 - mae: 34.7508 - val_loss: 11702.2480 - val_mae: 36.4997
Epoch 52/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7336.2397 - mae: 34.8513 - val_loss: 12514.7969 - val_mae: 39.8240
Epoch 53/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7548.0703 - mae: 34.9593 - val_loss: 11615.8721 - val_mae: 36.4284
Epoch 54/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7098.9082 - mae: 34.0743 - val_loss: 11750.4238 - val_mae: 36.4336
Epoch 55/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7018.5391 - mae: 34.3751 - val_loss: 12467.8721 - val_mae: 37.6316
Epoch 56/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7177.5698 - mae: 34.3236 - val_loss: 11363.0596 - val_mae: 36.8029
Epoch 57/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7464.6655 - mae: 33.8419 - val_loss: 12604.6562 - val_mae: 37.8787
Epoch 58/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6976.4282 - mae: 33.7819 - val_loss: 12315.9902 - val_mae: 36.9303
Epoch 59/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7209.8130 - mae: 34.4447 - val_loss: 13251.7373 - val_mae: 37.4656
Epoch 60/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7125.0444 - mae: 34.1865 - val_loss: 11741.6309 - val_mae: 36.2185

## Evaluate the Model

In [7]:
mse, mae = model.evaluate(X_test_scaled, y_test)
print(f"Test Mean Absolute Error (MAE): {mae:.2f}")

83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7754.2998 - mae: 35.5727
Test Mean Absolute Error (MAE): 35.57